source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.6'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
  # Required to use the Rails Panel extension in Chrome
  gem 'meta_request'
  # These two gems provide MUCH better error reporting for Rails in the browser
  gem 'better_errors' # better error in web browser
  gem 'binding_of_caller' # required for better_errors
  # Extend IRB to be more powerful
  gem 'irbtools-more', require: 'binding.repl'
  # gem 'terminal-notifier' # Used to send user notifications on Mac OS X from the command line
  # Pretty printing for Ruby objects in full color with proper indentation
  gem 'awesome_print'
  # A bunch of gems centered around Pry (IRB alternative): Pry, Awesome Print, Hirb, Pry Doc, and Pry Coolline
  gem 'jazz_fingers'
  # Mash pry and byebug together -- step-by-step debugging and stack nagiviation for Pry
  gem 'pry-byebug'   # This may or may not work with 2.1.2 either, so remove if you still get errorrs
  # Fancy helper for calling various map combinations
  gem 'map_by_method'
  # Fancy helper for calling various map combinations
  gem 'what_methods'
end

group :test do
  gem 'rails-controller-testing'
  gem 'minitest-reporters'
  gem 'guard'
  gem 'guard-minitest'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

